# Generated by Django 3.2.6 on 2022-12-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20221116_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('album_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('song_name', models.CharField(max_length=100)),
                ('song_type', models.CharField(max_length=100)),
                ('recorded_studio', models.CharField(max_length=100)),
                ('song_file', models.FileField(upload_to='songs')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.artist')),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.AddField(
            model_name='album',
            name='album_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.song'),
        ),
    ]
